# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['reduce_cardinality']

# Cell
def reduce_cardinality(df,categorical,keep_level=20):
    numclasses={}
    catclasses={}
    for c in df.columns:
        uni_cnt=(len(np.unique(df[[c]])))
        numclasses[c]=uni_cnt
        if uni_cnt>keep_level:
            df_group=df.groupby(c).agg(pred_rate=('target','mean'),cnt=('Name','count')).reset_index()\
                       .sort_values(['cnt','pred_rate'],ascending=False)[:keep_level]
            keep_list=df_group.iloc[:,0].tolist()
            df_new=df
            df_new[c]=np.where(~df_new[c].isin(keep_list),'OTHER',df_new[c])
            catclasses[c]=df_new.loc[:,c].unique().tolist()

    return df_new,catclasses